change github action

diff --git a/.github/workflows/android-build-release.yml b/.github/workflows/android-build-release.yml
--- a/.github/workflows/android-build-release.yml
+++ b/.github/workflows/android-build-release.yml
@@ -34,6 +34,13 @@ jobs:
           ./gradlew assembleRelease
         working-directory: ./  # Supposant que gradlew est dans le répertoire racine
 
+      - name: Vérifier l'APK généré
+        run: |
+          if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then
+            echo "APK not found!"
+            exit 1
+          fi
+
       - name: Obtenir la version de l'application
         id: get_version_name
         run: |
@@ -49,6 +56,10 @@ jobs:
           REQUEST_BODY=$(jq -n --arg tag_name "$TAG_NAME" --arg target_commitish "$GITHUB_SHA" --arg name "$RELEASE_NAME" --arg body "Automated release for version $TAG_NAME" '{ tag_name: $tag_name, target_commitish: $target_commitish, name: $name, body: $body, draft: false, prerelease: false }')
           RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "$REQUEST_BODY" "https://api.github.com/repos/${{ github.repository }}/releases")
           UPLOAD_URL=$(echo "$RESPONSE" | jq -r .upload_url | sed -e "s/{?name,label}//")
+          if [ "$UPLOAD_URL" == "null" ]; then
+            echo "Failed to get upload URL"
+            exit 1
+          fi
           echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
